"""initial schema

Revision ID: 80b43eafa829
Revises: 
Create Date: 2026-09-18 16:04:34.487928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80b43eafa829'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('device_code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_code'), 'devices', ['device_code'], unique=True)
    op.create_table('locations',
    sa.Column('aisle', sa.String(length=16), nullable=False),
    sa.Column('bay', sa.String(length=16), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('pos_x', sa.Float(), nullable=False),
    sa.Column('pos_y', sa.Float(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aisle', 'bay', 'level', name='uq_location_position')
    )
    op.create_index(op.f('ix_locations_barcode'), 'locations', ['barcode'], unique=True)
    op.create_table('operators',
    sa.Column('badge_code', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('pin_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('OPERATOR', 'SUPERVISOR', name='operatorrole', native_enum=False, length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operators_badge_code'), 'operators', ['badge_code'], unique=True)
    op.create_table('skus',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('voice_alias', sa.String(length=300), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skus_code'), 'skus', ['code'], unique=True)
    op.create_table('voice_clips',
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('voice_id', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('audio_format', sa.String(length=16), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_clips_content_hash'), 'voice_clips', ['content_hash'], unique=True)
    op.create_table('pick_sessions',
    sa.Column('operator_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('BASELINE', 'VOICE', name='sessionmode', native_enum=False, length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sku_barcodes',
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sku_barcodes_barcode'), 'sku_barcodes', ['barcode'], unique=True)
    op.create_table('stock_levels',
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_id', 'location_id', name='uq_stock_sku_location')
    )
    op.create_table('pick_orders',
    sa.Column('order_code', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='orderstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['pick_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pick_orders_order_code'), 'pick_orders', ['order_code'], unique=True)
    op.create_table('surveys',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=False),
    sa.Column('effort_score', sa.Integer(), nullable=False),
    sa.Column('fatigue_score', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['pick_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pick_lines',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('expected_qty', sa.Integer(), nullable=False),
    sa.Column('scan_each_unit', sa.Boolean(), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'AWAITING_LOCATION', 'AWAITING_SCAN', 'BLOCKED', 'NEEDS_OVERRIDE', 'AWAITING_QTY', 'SHORT_PENDING', 'DONE', 'EXCEPTED', name='pickstate', native_enum=False, length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('blocked_on', sa.Enum('LOCATION', 'SKU', 'QTY', name='blockedon', native_enum=False, length=20), nullable=True),
    sa.Column('last_qty', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['pick_orders.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('pick_line_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Enum('SHORT', 'EMPTY_LOCATION', 'DAMAGED', name='incidentreason', native_enum=False, length=20), nullable=False),
    sa.Column('reported_qty', sa.Integer(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pick_line_id'], ['pick_lines.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['pick_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pick_events',
    sa.Column('pick_line_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('client_event_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pick_line_id'], ['pick_lines.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['pick_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pick_events_client_event_id'), 'pick_events', ['client_event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pick_events_client_event_id'), table_name='pick_events')
    op.drop_table('pick_events')
    op.drop_table('incidents')
    op.drop_table('pick_lines')
    op.drop_table('surveys')
    op.drop_index(op.f('ix_pick_orders_order_code'), table_name='pick_orders')
    op.drop_table('pick_orders')
    op.drop_table('stock_levels')
    op.drop_index(op.f('ix_sku_barcodes_barcode'), table_name='sku_barcodes')
    op.drop_table('sku_barcodes')
    op.drop_table('pick_sessions')
    op.drop_index(op.f('ix_voice_clips_content_hash'), table_name='voice_clips')
    op.drop_table('voice_clips')
    op.drop_index(op.f('ix_skus_code'), table_name='skus')
    op.drop_table('skus')
    op.drop_index(op.f('ix_operators_badge_code'), table_name='operators')
    op.drop_table('operators')
    op.drop_index(op.f('ix_locations_barcode'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_devices_device_code'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
