"""wms stock movements ledger

Revision ID: a563f76c6c7e
Revises: 80b43eafa829
Create Date: 2026-09-18 16:14:44.561528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a563f76c6c7e'
down_revision: Union[str, Sequence[str], None] = '80b43eafa829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_movements',
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.Enum('RESERVE', 'COMMIT', 'RELEASE', name='movementtype', native_enum=False, length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movement_type', 'idempotency_key', name='uq_movement_idempotency')
    )
    op.create_index(op.f('ix_stock_movements_idempotency_key'), 'stock_movements', ['idempotency_key'], unique=False)
    op.add_column(
        'stock_levels',
        sa.Column('reserved_qty', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_levels', 'reserved_qty')
    op.drop_index(op.f('ix_stock_movements_idempotency_key'), table_name='stock_movements')
    op.drop_table('stock_movements')
    # ### end Alembic commands ###
